import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderDesktop } from "@/components/HeaderDesktop";
import { HeaderMobile } from "@/components/HeaderMobile";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderDesktop />
        <HeaderMobile />
        {children}
        <Footer />
        </body>
    </html>
  );
}
